spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
  http:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  jmx:
    enabled: false
  jackson: date-format=yyyy-MM-dd'T'HH:mm:ss.SSSZZZZ

#Ribbon
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1

# feign
feign:
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

#  hystrix
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
